name: Publish NuGet package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-pack-publish:
    name: Build, Pack, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release name
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "release_name=$REF_NAME-$TARGET" >> $GITHUB_ENV
          echo "BUILD_VERSION=${REF_NAME//v/}" >> $GITHUB_ENV

      - name: Echo vars
        run: |
          echo "Release name: ${{ env.release_name }} Build version: ${{ env.BUILD_VERSION }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./Bunny.LibSql.Client/Bunny.LibSql.Client.csproj --configuration Release --no-build --output ./artifacts /p:PackageId=EdoardoTona.Bunny.LibSql.Client

      - name: Publish to NuGet.org
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
